// optionsData.js

export const academicLevelOptions = [
  {
    value: "-- Please Select Academic Level --",
    label: "-- Please Select Academic Level --",
  },
  { value: "Masters", label: "Masters" },
  { value: "Undergraduate", label: "Undergraduate" },
  { value: "PhD", label: "PhD" },
];

export const domainOptions = [
  { value: "-- Please Select Domain --", label: "-- Please Select Domain --" },
  { value: "1", label: "Accounting & Finance" },
  { value: "49", label: "Advertising/Public Relations" },
  { value: "51", label: "Animal/Plant Biology" },
  { value: "52", label: "Anthropology" },
  { value: "53", label: "Archaeology" },
  { value: "54", label: "Architecture" },
  { value: "55", label: "Art" },
  { value: "186", label: "BioInformatics" },
  { value: "56", label: "Biology Studies" },
  { value: "57", label: "Business" },
  { value: "189", label: "Business Analytics" },
  { value: "58", label: "Chemistry" },
  { value: "59", label: "Children & Young People" },
  { value: "3", label: "Civil" },
  { value: "60", label: "Civil Litigation Law" },
  { value: "61", label: "Commercial Law" },
  { value: "62", label: "Commercial Property Law" },
  { value: "63", label: "Communications" },
  { value: "65", label: "Comparative/Conflict of Laws" },
  { value: "66", label: "Competition Law" },
  { value: "4", label: "Computer Science" },
  { value: "69", label: "Construction" },
  { value: "70", label: "Construction Law" },
  { value: "71", label: "Contract Law" },
  { value: "72", label: "Counselling" },
  { value: "74", label: "Criminal Law" },
  { value: "75", label: "Criminal Litigation (Law)" },
  { value: "76", label: "Criminology" },
  { value: "77", label: "Cultural Studies" },
  { value: "78", label: "Dentistry" },
  { value: "79", label: "Design" },
  { value: "80", label: "Drama" },
  { value: "5", label: "Economics" },
  { value: "82", label: "Economics (Social Sciences)" },
  { value: "83", label: "Education" },
  { value: "84", label: "Employment" },
  { value: "85", label: "Employment Law" },
  { value: "86", label: "Engineering" },
  { value: "87", label: "English Language" },
  { value: "88", label: "English Legal System (Law)" },
  { value: "89", label: "English Literature" },
  { value: "90", label: "Environment" },
  { value: "91", label: "Environmental Sciences" },
  { value: "92", label: "Environmental/Planning Law" },
  { value: "188", label: "Entrepreneurship" },
  { value: "93", label: "Equity & Trusts Law" },
  { value: "94", label: "Estate Management" },
  { value: "95", label: "European (EU) Law" },
  { value: "96", label: "European Studies" },
  { value: "97", label: "Family Law" },
  { value: "98", label: "Fashion" },
  { value: "99", label: "Film Studies" },
  { value: "100", label: "Finance" },
  { value: "101", label: "Finance Law" },
  { value: "190", label: "Financial Analysis" },
  { value: "102", label: "Food and Nutrition" },
  { value: "103", label: "Forensic Science" },
  { value: "104", label: "French" },
  { value: "105", label: "General Law" },
  { value: "106", label: "Geography" },
  { value: "107", label: "Geology" },
  { value: "108", label: "German" },
  { value: "109", label: "Health" },
  { value: "110", label: "Health & Social Care" },
  { value: "111", label: "Health and Safety" },
  { value: "112", label: "Health Psychology" },
  { value: "113", label: "History" },
  { value: "6", label: "Hospitality" },
  { value: "114", label: "Housing" },
  { value: "7", label: "HRM" },
  { value: "115", label: "Human Resource Management" },
  { value: "116", label: "Human Rights" },
  { value: "117", label: "Human Rights Law" },
  { value: "118", label: "Immigration/Refugee Law" },
  { value: "120", label: "Information Systems" },
  { value: "121", label: "Information Technology" },
  { value: "122", label: "Intellectual Property Law" },
  { value: "8", label: "International Business" },
  { value: "123", label: "International Commercial Law" },
  { value: "124", label: "International Criminal Law" },
  { value: "125", label: "International Law" },
  { value: "127", label: "International Relations" },
  { value: "128", label: "International Studies" },
  { value: "129", label: "Jurisprudence (Law)" },
  { value: "130", label: "Land/property Law" },
  { value: "131", label: "Landlord & Tenant/Housing Law" },
  { value: "9", label: "Law" },
  { value: "132", label: "Law of Evidence" },
  { value: "134", label: "Linguistics" },
  { value: "10", label: "Literature" },
  { value: "11", label: "Management" },
  { value: "136", label: "Maritime Law" },
  { value: "12", label: "Marketing" },
  { value: "138", label: "Maths" },
  { value: "2", label: "Mechanical" },
  { value: "139", label: "Media" },
  { value: "13", label: "Medical" },
  { value: "140", label: "Medical Law" },
  { value: "141", label: "Medicine" },
  { value: "142", label: "Mental Health" },
  { value: "143", label: "Mental Health Law" },
  { value: "144", label: "Methodology" },
  { value: "145", label: "Music" },
  { value: "146", label: "Nursing" },
  { value: "147", label: "Occupational Therapy" },
  { value: "148", label: "Oil & Gas Law" },
  { value: "149", label: "Other" },
  { value: "16", label: "Others" },
  { value: "150", label: "Paramedic Studies" },
  { value: "151", label: "Pharmacology" },
  { value: "152", label: "Philosophy" },
  { value: "153", label: "Photography" },
  { value: "154", label: "Physical Education" },
  { value: "155", label: "Physics" },
  { value: "156", label: "Physiotherapy" },
  { value: "14", label: "Politics" },
  { value: "158", label: "Professional Conduct Law" },
  { value: "191", label: "Project Management" },
  { value: "15", label: "Psychology" },
  { value: "160", label: "Psychotherapy" },
  { value: "161", label: "Public Administration" },
  { value: "162", label: "Public Law" },
  { value: "163", label: "Quantity Surveying" },
  { value: "164", label: "Radiology & Medical Technology" },
  { value: "165", label: "Real Estate" },
  { value: "166", label: "Security & Risk Management" },
  { value: "167", label: "Social Policy" },
  { value: "168", label: "Social Work" },
  { value: "169", label: "Social Work Law" },
  { value: "170", label: "Sociology" },
  { value: "171", label: "Spanish" },
  { value: "172", label: "Sports Law" },
  { value: "173", label: "Sports Psychology" },
  { value: "174", label: "Sports Science" },
  { value: "175", label: "SPSS" },
  { value: "176", label: "Statistics" },
  { value: "192", label: "Strategy Management" },
  { value: "187", label: "Supply Chain Management" },
  { value: "177", label: "Tax Law" },
  { value: "178", label: "Teacher Training / PGCE" },
  { value: "179", label: "TESOL" },
  { value: "180", label: "Theatre Studies" },
  { value: "181", label: "Theology & Religion" },
  { value: "182", label: "Tort Law" },
  { value: "183", label: "Tourism & Hospitality" },
  { value: "184", label: "Town & Country Planning" },
  { value: "185", label: "Translation" },
];

export const desiredServiceOptions = [
  {
    value: "-- Please Select Desired Service --",
    label: "-- Please Select Desired Service --",
  },
  { value: "2;1,3", label: "Assignment" },
  { value: "3;1,3", label: "Coursework" },
  { value: "4;1,3", label: "Essay" },
  { value: "9;1,3", label: "Dissertation" },
  { value: "16;1,3", label: "High Index Journal" },
  { value: "1;1,3", label: "PhD Admission Proposal" },
];

export const wordsPagesOptions = [
  {
    value: "-- Select No. of Words/Pages --",
    label: "-- Select No. of Words/Pages --",
  },
  { value: "1000", label: "1000 words ~ 4 pages" },
  { value: "1500", label: "1500 words ~ 6 pages" },
  { value: "2000", label: "2000 words ~ 8 pages" },
  { value: "2500", label: "2500 words ~ 10 pages" },
  { value: "3000", label: "3000 words ~ 12 pages" },
  { value: "3500", label: "3500 words ~ 14 pages" },
  { value: "4000", label: "4000 words ~ 16 pages" },
  { value: "4500", label: "4500 words ~ 18 pages" },
  { value: "5000", label: "5000 words ~ 20 pages" },
  { value: "5500", label: "5500 words ~ 22 pages" },
  { value: "6000", label: "6000 words ~ 24 pages" },
  { value: "6500", label: "6500 words ~ 26 pages" },
  { value: "7000", label: "7000 words ~ 28 pages" },
  { value: "7500", label: "7500 words ~ 30 pages" },
  { value: "8000", label: "8000 words ~ 32 pages" },
  { value: "9000", label: "9000 words ~ 36 pages" },
  { value: "10000", label: "10000 words ~ 40 pages" },
  { value: "11000", label: "11000 words ~ 44 pages" },
  { value: "12000", label: "12000 words ~ 48 pages" },
  { value: "13000", label: "13000 words ~ 52 pages" },
  { value: "14000", label: "14000 words ~ 56 pages" },
  { value: "15000", label: "15000 words ~ 60 pages" },
  { value: "16000", label: "16000 words ~ 64 pages" },
  { value: "17000", label: "17000 words ~ 68 pages" },
  { value: "18000", label: "18000 words ~ 72 pages" },
  { value: "19000", label: "19000 words ~ 76 pages" },
  { value: "20000", label: "20000 words ~ 80 pages" },
  { value: "21000", label: "21000 words ~ 84 pages" },
  { value: "22000", label: "22000 words ~ 88 pages" },
  { value: "23000", label: "23000 words ~ 92 pages" },
  { value: "24000", label: "24000 words ~ 96 pages" },
  { value: "25000", label: "25000 words ~ 100 pages" },
  { value: "26000", label: "26000 words ~ 104 pages" },
  { value: "27000", label: "27000 words ~ 108 pages" },
  { value: "28000", label: "28000 words ~ 112 pages" },
  { value: "29000", label: "29000 words ~ 116 pages" },
  { value: "30000", label: "30000 words ~ 120 pages" },
];

export const toolOptions = [
  { value: "-- Select Tool --", label: "-- Select Tool --" },
  { value: "NA", label: "None" },
  { value: "SPSS", label: "SPSS" },
  { value: "STATA", label: "STATA" },
  { value: "Eviews", label: "Eviews" },
  { value: "Nvivo", label: "Nvivo" },
  { value: "Xls Analysis", label: "Xls Analysis" },
  { value: "R Programming", label: "R Programming" },
];
